version: '2'
services:
  elasticsearch:
    build: "./Elasticsearch"
    image: "graylog-elasticsearch"
    command: "elasticsearch -Des.node.master=true -Des.node.data=true -Des.cluster.name='graylog'"
    restart: "always"
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"

  mongodb:
    build: "./Mongodb"
    image: "graylog-mongodb"

  graylog:
    build: "./"
    image: "graylog"
    depends_on:
      - "elasticsearch"
      - "mongodb"
    environment:
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_REST_TRANSPORT_URI: "http://127.0.0.1:12900"
    links:
      - "mongodb:mongo"
      - "elasticsearch:elasticsearch"
    ports:
      - "1514:1514/udp"
      - "9000:9000"
      - "12900:12900"

volumes:
  elasticsearch:
